### ISSUE TITLE
Add a few instances of example_random

### ISSUE THREAD

**Issue by RichiH** [prometheus/demo-site#3]

**Comment by infoverload** [comment]
@RichiH Could you provide more information about this issue?

**Comment by paulfantom** [comment]
I believe example_random is an instance of https://github.com/prometheus/client_golang/blob/master/examples/random/main.go

**Comment by RichiH** [comment]
Sorry this reply got stuck in email drafts. This is correct.

Sent by mobile; please excuse my brevity.

**Comment by paulfantom** [comment]
This is already done in an upstream version of the site: https://github.com/cloudalchemy/demo-site/blob/master/extras.yml#L134-L180
