### ISSUE TITLE
The conditional check 'caddy_features | search('git')' failed. 

### ISSUE THREAD

**Issue by nirmalpathak** [prometheus/demo-site#34]
**Issue:**
The ansible playbook fails a condition check while installing 'git' using apt on Ubuntu 20.04 LTS.

**Error:**
TASK [caddy_ansible.caddy_ansible : Install git] ************************************************************************************************************************
fatal: [demo]: FAILED! => {"msg": "The conditional check 'caddy_features | search('git')' failed. The error was: template error while templating string: no filter named 'search'. String: {% if caddy_features | search('git') %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/npathak/sonic-jobs/ansible/demo-site/roles/caddy_ansible.caddy_ansible/tasks/packages-apt.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install git\n  ^ here\n"}

**Details:**
- The failing condition is set in caddy_ansible role in a file `roles/caddy_ansible.caddy_ansible/tasks/packages-apt.yml`.
- Commenting the condition check `#when: caddy_features | search('git')`works.

**Comment by paulfantom** [comment]
This is a failure in an ansible role on which we depend. Please open issue in https://github.com/caddy-ansible/caddy-ansible.
