### ISSUE TITLE
Unable to start service caddy.

### ISSUE THREAD

**Issue by nirmalpathak** [prometheus/demo-site#35]
**Issue:**
Unable to start/restart caddy service on Ubuntu 20.04 LTS

**Error:**
RUNNING HANDLER [caddy_ansible.caddy_ansible : reload caddy] ************************************************************************************************************
fatal: [demo]: FAILED! => {"changed": false, "msg": "Unable to start service caddy: Job for caddy.service failed because the control process exited with error code.\nSee \"systemctl status caddy.service\" and \"journalctl -xe\" for details.\n"}

**Details:**
- The permission of the directory `/var/www` is set to 750 after OS hardening.
- Manually changing the permission of the directory `/var/www` to 755 works.

**Comment by paulfantom** [comment]
This is a failure in an ansible role on which we depend. Please open issue in https://github.com/caddy-ansible/caddy-ansible.
