### ISSUE TITLE
ERROR! Invalid vault password was provided from file (/tmp/vault)

### ISSUE THREAD

**Issue by ldoublewood** [prometheus/demo-site#38]
run deploy.sh, then above error message occur

**Comment by ldoublewood** [comment]
Why you close this issue without any comment?

**Comment by paulfantom** [comment]
> ERROR! Invalid vault password was provided from file

You need to configure your own secrets. More on the topic in https://docs.ansible.com/ansible/latest/user_guide/vault.html
