### ISSUE TITLE
prometheus 1.7.1 on demo site

### ISSUE THREAD

**Issue by paulfantom** [prometheus/demo-site#4]
Current [demo site presents prometheus in version 1.7.1](http://demo.prometheus.io:9090/status) which is a little bit old. Maybe it would be nice to upgrade it to 2.x ?

Can I help somehow to get this repo to power demo.prometheus.io site?

**Comment by SuperQ** [comment]
Yes, I was setting up a new demo server. Right now it's `demo.do.prometheus.io`, I haven't had the time to finish setting it up and point the old demo site DNS to it.
